# Generated by Django 5.2.3 on 2025-06-21 13:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کتاب')),
                ('author', models.CharField(max_length=100, verbose_name='نویسنده')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='شابک')),
                ('genre', models.CharField(choices=[('رمان', 'رمان'), ('علمی', 'علمی'), ('تاریخی', 'تاریخی'), ('روانشناسی', 'روانشناسی'), ('فلسفه', 'فلسفه'), ('پزشکی', 'پزشکی')], max_length=50, verbose_name='ژانر')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد کل')),
                ('available', models.PositiveIntegerField(default=1, verbose_name='موجودی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('member_id', models.CharField(max_length=10, unique=True, verbose_name='شماره عضویت')),
                ('student_id', models.CharField(blank=True, max_length=20, verbose_name='شماره دانشجویی')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='تلفن')),
                ('membership_end', models.DateField(verbose_name='تاریخ انقضا')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'عضو',
                'verbose_name_plural': 'اعضا',
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True, verbose_name='تاریخ امانت')),
                ('due_date', models.DateField(verbose_name='موعد برگشت')),
                ('returned', models.BooleanField(default=False, verbose_name='برگشت داده شده؟')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='تاریخ برگشت')),
                ('fine', models.PositiveIntegerField(default=0, verbose_name='جریمه')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='کتاب')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.member', verbose_name='عضو')),
            ],
            options={
                'verbose_name': 'سابقه امانت',
                'verbose_name_plural': 'سوابق امانت',
            },
        ),
    ]
