# Generated by Django 5.2.3 on 2025-06-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowrecord',
            options={'ordering': ['-borrow_date'], 'verbose_name': 'سابقه امانت', 'verbose_name_plural': 'سوابق امانت'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('رمان', 'رمان'), ('علمی', 'علمی'), ('تاریخی', 'تاریخی'), ('پزشکی', 'پزشکی')], max_length=50, verbose_name='ژانر'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='fine',
            field=models.PositiveIntegerField(default=0, verbose_name='جریمه (تومان)'),
        ),
    ]
