# Generated by Django 5.2.3 on 2025-06-22 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover_book_pages_book_publish_year_and_more'),
    ]

    operations = [
    ]
