# Generated by Django 5.2.3 on 2025-06-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20250622_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'کتاب', 'verbose_name_plural': 'کتاب\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'عضو', 'verbose_name_plural': 'اعضا'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.AddField(
            model_name='member',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(default='User', max_length=100, verbose_name='نام خانوادگی'),
        ),
    ]
