# Generated by Django 5.2.3 on 2025-06-22 01:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_options_alter_member_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowrecord',
            options={'ordering': ['-borrow_date'], 'permissions': [('can_renew_borrowing', 'می\u200cتواند امانت را تمدید کند')], 'verbose_name': 'سابقه امانت', 'verbose_name_plural': 'سوابق امانت'},
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AddField(
            model_name='book',
            name='physical_condition',
            field=models.CharField(choices=[('excellent', 'عالی'), ('good', 'خوب'), ('fair', 'متوسط'), ('poor', 'ضعیف'), ('damaged', 'آسیب دیده')], default='good', max_length=15, verbose_name='وضعیت فیزیکی'),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'موجود'), ('borrowed', 'امانت داده شده'), ('reserved', 'رزرو شده'), ('maintenance', 'در حال تعمیر')], default='available', max_length=15, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت\u200cها'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='renewal_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد تمدید'),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='member',
            name='max_borrow_limit',
            field=models.PositiveIntegerField(default=3, verbose_name='حداکثر تعداد امانت'),
        ),
        migrations.AddField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('student', 'دانشجو'), ('professor', 'استاد'), ('staff', 'کارمند'), ('guest', 'میهمان')], default='student', max_length=10, verbose_name='نوع عضو'),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ شروع عضویت'),
        ),
        migrations.AddField(
            model_name='member',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت\u200cها'),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, unique=True, verbose_name='شابک (ISBN)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)], verbose_name='سال انتشار'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=100, verbose_name='ناشر'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان کتاب'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='books.book', verbose_name='کتاب'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrow_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ امانت'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='books.member', verbose_name='عضو'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='member',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره دانشجویی/پرسنلی'),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ژانر')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.genre', verbose_name='ژانر والد')),
            ],
            options={
                'verbose_name': 'ژانر',
                'verbose_name_plural': 'ژانرها',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.genre', verbose_name='ژانر'),
        ),
    ]
